const PIXELPERUNIT = 24;
const PIXEL = 1 / PIXELPERUNIT;

const SECOND = 1000;
const MILLISECOND = 1 / SECOND;

const MAXUNITCOUNT = 5;

export { PIXELPERUNIT, PIXEL, SECOND, MILLISECOND, MAXUNITCOUNT };
