const UNITTYPE =
  //Object.freeze({
  {
    gold: {
      texture: 'gold',
      attackSpeed: 0.5,
      attackSpeedIncrease: 0.01,
      speed: 0.75,
      speedIncrease: 0,
      strength: 1,
      strengthIncrease: 0.05,
      bulletTexture: 'lightParticle',
      attack: true,
      //descript: 'Gain gold when combine',
      descript: '합성할 때 골드를 획득.',
    },
    plant: {
      texture: 'plant',
      attackSpeed: 0.25,
      attackSpeedIncrease: 0,
      speed: 0.2,
      speedIncrease: 0,
      strength: 1,
      strengthIncrease: 0.2,
      bulletTexture: 'bullet',
      attack: false,
      // descript: "Gain gold every 4 seconds, but can't attack",
      descript: '공격대신 골드를 획득.',
    },
    gem: {
      texture: 'gem',
      attackSpeed: 0.5,
      attackSpeedIncrease: 0,
      speed: 0.2,
      speedIncrease: 0,
      strength: 4,
      strengthIncrease: 0.2,
      bulletTexture: 'littleGem',
      attack: true,
      descript: '랭크가 같다면 종류가 달라도 합성 가능',
    },
    egg: {
      texture: 'egg',
      attackSpeed: 0.2,
      attackSpeedIncrease: 0,
      speed: 1,
      speedIncrease: 0,
      strength: 1,
      strengthIncrease: 1,
      bulletTexture: undefined,
      attack: false,
      descript: '합성하면 랭크만큼의 랜덤유닛을 생성',
    },
    sugar: {
      texture: 'sugar',
      attackSpeed: 1,
      attackSpeedIncrease: 0.05,
      speed: 0.5,
      speedIncrease: 0,
      strength: 1,
      strengthIncrease: 0.01,
      bulletTexture: 'sugarParticle',
      attack: true,
      descript: '공격속도가 증가',
    },
    orgol: {
      texture: 'orgol',
      attackSpeed: 2,
      attackSpeedIncrease: 0.02,
      speed: 0.5,
      speedIncrease: 0,
      strength: 1,
      strengthIncrease: 0.01,
      bulletTexture: 'note',
      attack: true,
      descript: '랭크가 같다면 종류가 달라도 합성 가능',
    },
  };
//});

export { UNITTYPE };
